name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BLOB_HOST: ${{ secrets.BLOB_HOST }}
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      NEXT_PUBLIC_BLOB_HOST: ${{ secrets.NEXT_PUBLIC_BLOB_HOST }}
      NEXT_PUBLIC_BUNJANG_MEDIA_HOST: ${{ secrets.NEXT_PUBLIC_BUNJANG_MEDIA_HOST }}
      NEXT_PUBLIC_KAKAO_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_KEY }}
      NEXT_PUBLIC_SERVER_HOST: ${{ secrets.NEXT_PUBLIC_SERVER_HOST }}
      NEXT_PUBLIC_WS_HOST: ${{ secrets.NEXT_PUBLIC_WS_HOST }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm prettier --check .

      - name: Build check
        run: pnpm build
